"""
Continuous Learning을 위한 학습 모듈
HITL 피드백 데이터를 사용하여 모델 성능 개선
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Dict, Any
from datetime import datetime

from agent.training.data_collector import DataCollector, TrainingDataset

logger = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """학습 설정"""
    epochs: int = 10
    batch_size: int = 8
    learning_rate: float = 1e-4
    warmup_steps: int = 100
    save_steps: int = 500
    eval_steps: int = 100
    output_dir: str = "./training_output"


class ContinuousLearningTrainer:
    """
    Continuous Learning 트레이너
    
    Note: 이 클래스는 학습 파이프라인의 인터페이스를 제공합니다.
    실제 모델 fine-tuning은 별도의 GPU 환경에서 실행해야 합니다.
    """
    
    def __init__(
        self,
        feedback_db_path: str = "./feedback.db",
        training_config: Optional[TrainingConfig] = None,
    ):
        """
        Args:
            feedback_db_path: 피드백 DB 경로
            training_config: 학습 설정
        """
        self.data_collector = DataCollector(feedback_db_path)
        self.config = training_config or TrainingConfig()
        logger.info("ContinuousLearningTrainer 초기화 완료")
    
    def prepare_training_data(
        self,
        output_dir: Optional[str] = None,
        format: str = "coco",
    ) -> TrainingDataset:
        """
        학습 데이터 준비
        
        Args:
            output_dir: 출력 디렉토리
            format: 출력 포맷 ("coco" or "yolo")
            
        Returns:
            TrainingDataset 객체
        """
        if output_dir is None:
            output_dir = self.config.output_dir
        
        output_path = Path(output_dir) / "dataset"
        
        logger.info(f"학습 데이터 준비 시작: {output_path}")
        
        dataset = self.data_collector.collect_approved_data(
            output_dir=str(output_path),
            format=format,
            include_corrected=True,
            copy_images=True,
        )
        
        return dataset
    
    def check_training_readiness(self) -> Dict[str, Any]:
        """
        학습 준비 상태 확인
        
        Returns:
            준비 상태 정보
        """
        stats = self.data_collector.get_collection_stats()
        
        min_samples = 10  # 최소 필요 샘플 수
        available = stats["available_for_training"]
        
        ready = available >= min_samples
        
        result = {
            "ready": ready,
            "available_samples": available,
            "min_required": min_samples,
            "stats": stats,
        }
        
        if not ready:
            result["message"] = f"최소 {min_samples}개 샘플이 필요합니다. 현재: {available}개"
        else:
            result["message"] = f"학습 준비 완료. {available}개 샘플 사용 가능"
        
        return result
    
    def generate_training_script(
        self,
        dataset: TrainingDataset,
        output_path: str = "./train.sh",
        model_type: str = "dino",
    ) -> str:
        """
        학습 스크립트 생성
        
        Note: 실제 학습은 별도의 GPU 환경에서 이 스크립트를 실행해야 합니다.
        
        Args:
            dataset: 준비된 데이터셋
            output_path: 스크립트 출력 경로
            model_type: 모델 타입 ("dino" or "sam")
            
        Returns:
            생성된 스크립트 경로
        """
        if model_type == "dino":
            script = self._generate_dino_training_script(dataset)
        elif model_type == "sam":
            script = self._generate_sam_training_script(dataset)
        else:
            raise ValueError(f"지원하지 않는 모델 타입: {model_type}")
        
        with open(output_path, 'w') as f:
            f.write(script)
        
        logger.info(f"학습 스크립트 생성: {output_path}")
        return output_path
    
    def _generate_dino_training_script(self, dataset: TrainingDataset) -> str:
        """DINO 학습 스크립트 생성"""
        return f'''#!/bin/bash
# DINO Fine-tuning Script
# Generated by DINO-SAM Labeling Agent
# Date: {datetime.now().isoformat()}

# 데이터셋 경로
DATASET_DIR="{dataset.output_dir}"
OUTPUT_DIR="{self.config.output_dir}/dino_finetuned"

# 학습 설정
EPOCHS={self.config.epochs}
BATCH_SIZE={self.config.batch_size}
LR={self.config.learning_rate}

echo "==================================="
echo "DINO Fine-tuning"
echo "Dataset: $DATASET_DIR"
echo "Output: $OUTPUT_DIR"
echo "==================================="

# GroundingDINO 설치 확인
if ! python -c "import groundingdino" 2>/dev/null; then
    echo "Error: GroundingDINO가 설치되지 않았습니다."
    echo "pip install groundingdino-py"
    exit 1
fi

# Fine-tuning 실행
# Note: 실제 DINO fine-tuning 코드는 GroundingDINO 리포지토리 참조
# https://github.com/IDEA-Research/GroundingDINO

echo "Fine-tuning 스크립트 준비가 완료되었습니다."
echo "GroundingDINO의 공식 fine-tuning 가이드를 참조하세요."
'''
    
    def _generate_sam_training_script(self, dataset: TrainingDataset) -> str:
        """SAM 학습 스크립트 생성"""
        return f'''#!/bin/bash
# SAM Fine-tuning Script
# Generated by DINO-SAM Labeling Agent
# Date: {datetime.now().isoformat()}

# 데이터셋 경로
DATASET_DIR="{dataset.output_dir}"
OUTPUT_DIR="{self.config.output_dir}/sam_finetuned"

# 학습 설정
EPOCHS={self.config.epochs}
BATCH_SIZE={self.config.batch_size}
LR={self.config.learning_rate}

echo "==================================="
echo "SAM Fine-tuning"
echo "Dataset: $DATASET_DIR"
echo "Output: $OUTPUT_DIR"
echo "==================================="

# SAM 설치 확인
if ! python -c "from segment_anything import sam_model_registry" 2>/dev/null; then
    echo "Error: SAM이 설치되지 않았습니다."
    echo "pip install git+https://github.com/facebookresearch/segment-anything.git"
    exit 1
fi

# Fine-tuning 실행
# Note: 실제 SAM fine-tuning 코드는 segment-anything 리포지토리 참조
# https://github.com/facebookresearch/segment-anything

echo "Fine-tuning 스크립트 준비가 완료되었습니다."
echo "SAM의 공식 fine-tuning 가이드를 참조하세요."
'''
    
    def create_training_report(self) -> Dict[str, Any]:
        """학습 준비 리포트 생성"""
        readiness = self.check_training_readiness()
        stats = self.data_collector.get_collection_stats()
        
        report = {
            "timestamp": datetime.now().isoformat(),
            "data_summary": {
                "total_approved": stats["total_approved"],
                "total_corrected": stats["total_corrected"],
                "total_available": stats["available_for_training"],
                "pending_review": stats["pending_review"],
                "rejected": stats["rejected"],
            },
            "training_readiness": {
                "ready": readiness["ready"],
                "message": readiness["message"],
            },
            "recommendations": [],
        }
        
        # 추천 사항 추가
        if not readiness["ready"]:
            report["recommendations"].append(
                f"더 많은 샘플을 승인하세요. "
                f"현재 {stats['available_for_training']}개, 필요: {readiness['min_required']}개"
            )
        
        if stats["pending_review"] > 0:
            report["recommendations"].append(
                f"{stats['pending_review']}개의 리뷰 대기 중인 샘플이 있습니다."
            )
        
        return report
